steps:
- name: 'gcr.io/jaypatel-100853189/cloud-builders/docker'
  args: ['build', '-t', 'intense-howl-412323/jaypatel-100853189/jay-image:$COMMIT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'intense-howl-412323/jaypatel-100853189/jay-image:$COMMIT_SHA']
options:
    defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

images: ['intense-howl-412323/jaypatel-100853189/jay-image:$COMMIT_SHA']
