steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/intense-howl-412323/jaypatel-100853189:$COMMIT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/intense-howl-412323/jaypatel-100853189:$COMMIT_SHA']
options:
    defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

images: ['gcr.io/intense-howl-412323/jaypatel-100853189:$COMMIT_SHA']
