steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/intense-howl-412323/jaypatel-100853189:$COMMIT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/intense-howl-412323/jaypatel-100853189:$COMMIT_SHA']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy kushal-image \
          --image us-central1-docker.pkg.dev/intense-howl-412323/jaypatel-100853189:$COMMIT_SHA \
          --platform managed \
          --region us-central1


options:
    defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

images: ['gcr.io/intense-howl-412323/jaypatel-100853189:$COMMIT_SHA']
